### ISSUE TITLE
READ recommendation

### ISSUE THREAD

**Issue by GEOGILBERT77** [DevOps-TeamRecommend/recommendations#4]
**As a** category manager
**I need** to access product recommendations
**So that** I can access related or relevant premium products with target products

**Assumptions:**
* Product IDs exist for recommendations to be applied to

**Acceptance Criteria:**
Product IDs associated with target product can be pulled from recommendation database

Given a product
```
When a category manager wants to associate recommended products to a target product
Then the category manager will be able to access associated product IDs from the recommendation database
```

**Comment by devneel** [comment]
Need to communicate with products group to determine their table structure
