### ISSUE TITLE
Action on a recommendation

### ISSUE THREAD

**Issue by cmf618** [DevOps-TeamRecommend/recommendations#8]
**As a** Category Manager
**I need** to be able to change my recommendations
**So that** they can stay accurate on the site 

**Assumptions:**
* recommendations will have an attribute that needs to be altered 

**Acceptance Criteria:**
```

Given I need to change a recommendation
When I call the specific recommendation id and change the value
Then it will update and save
```

**Comment by GEOGILBERT77** [comment]
How is a recommendation determined to be in need of an edit - just by manual review of a cat manager?  Or should there be an automated check against existing recommendations based on product discontinue, new product offering, change in purchasing behaviors, etc.?

**Comment by GEOGILBERT77** [comment]
Do we have an update function from the **recommendations** team to take into account new products, discontinued products and changes in purchasing behavior?  I.e., once a rec is created, is only a cat manager able to edit or can we?  If both, what are override authorities?

**Comment by GEOGILBERT77** [comment]
Since this is a manual updating process, should we have a notification function that alerts category managers to event (new products, discontinued products, change in recommendation) so they know when they need to take action?
